#!/usr/bin/env python3
# Deploy ONE Frappe site into a golden bench VM — run INSIDE the guest over
# guest-SSH (spec/14-self-serve.md), driven by the controller
# `atlas.atlas.deploy_site.deploy_site`. The golden image (spec/08-images.md)
# already baked bench-cli + `bench init` AND a fully-created site under the fixed
# name `site.local`, brought up production-style and (warm) frozen serving. So the
# ONLY per-VM work the image can't bake is giving that baked site its per-VM
# identity — the FQDN — on disk.
#
# RENAME model (Contract A): the baked `site.local` is renamed to the per-VM FQDN
# at deploy time, so the on-disk site name == the proxy Host header == the Site
# key (one routing string, never transformed). The production gunicorn is
# MULTITENANT — `frappe.app:application` runs with no fixed `--site`, so it
# resolves the site from the request `Host` header PER REQUEST (frappe/app.py
# `get_site_name(request.host)`), with nothing cached at boot. The proxy forwards
# `Host: <fqdn>`, so once `sites/<fqdn>` exists on disk and the bench's nginx vhost
# carries `server_name <fqdn>`, the running gunicorn serves it with NO restart.
# This is the latency win: the deploy is a directory rename + an nginx config
# regenerate + reload — no `bench new-site` (baked), no `set-admin-password` (the
# baked throwaway is rotated out of band), no `setup production`, and crucially NO
# restart of gunicorn/supervisor.
#
# The vhost is regenerated by `bench setup nginx` (NOT `setup production`): that is
# pure bench-cli config-gen — it scans `sites/` (so it discovers the renamed
# `<fqdn>` dir and emits `server_name <fqdn>` + a `root .../sites/<fqdn>/public`
# files block), `nginx -t`, then `systemctl reload nginx`. No Frappe/gunicorn boot,
# no process restart — sub-second. We then add the IPv6 listener bench-cli omits
# (the edge proxy reaches the VM over its public /128 only) and reload once more.
#
# This ships in the committed `bench/` tree (beside build.sh), uploaded verbatim
# and run over guest-SSH — the same idiom as build.sh. It is self-contained
# (stdlib only, no host `scripts/lib`): the guest never has the Atlas package, so
# the typed-task shape (kebab-case flags via argparse, one `ATLAS_RESULT={json}`
# line out) is inlined here rather than imported.
#
# Run as root with the baked PATH (build.sh wrote /etc/profile.d/atlas-bench.sh,
# but an SSH `command` is non-interactive and does NOT source profile.d, so the
# controller invokes us with an explicit interpreter + the bench-cli path passed
# in). Idempotent (spec taste #14: retry = re-run): a re-run finds `sites/<fqdn>`
# already in place (the baked `site.local` is gone) and just re-asserts the vhost
# + serving.

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass

RESULT_MARKER = "ATLAS_RESULT="

# Where build.sh installed bench-cli and the baked bench. Kept in lockstep with
# bench/build.sh (BENCH_CLI_DIR / BENCH_NAME) — if the bake moves them, move them
# here too. The site lives under <bench>/sites/<fqdn> after the rename.
BENCH_CLI_DIR = "/root/bench-cli"
BENCH_NAME = "atlas"
BENCH_DIR = f"{BENCH_CLI_DIR}/benches/{BENCH_NAME}"
BENCH = f"{BENCH_CLI_DIR}/bench"

# The site baked into the golden image (bench/build.sh BAKED_SITE). The per-site
# deploy renames this directory to the FQDN; a clone that doesn't carry it was
# built from the wrong/old (site-less) snapshot — _preflight fails loud on that.
BAKED_SITE = "site.local"
SITES_DIR = f"{BENCH_DIR}/sites"
# bench-cli writes one nginx vhost per site, named `<site>.conf`, under here.
# `bench setup nginx` only ever WRITES the current sites' confs — it never deletes
# stale ones — so after the rename we remove the baked `site.local.conf` ourselves,
# or its `server_name site.local` block would linger beside the new `<fqdn>` one.
NGINX_SITES_DIR = f"{BENCH_DIR}/config/nginx/sites"

# uv lands here; bench-cli shells out to it. A non-interactive SSH command does
# not source /etc/profile.d, so put the baked dirs on PATH explicitly.
BAKED_PATH = f"{BENCH_CLI_DIR}:/root/.local/bin"


@dataclass(frozen=True)
class DeploySiteInputs:
	"""Per-site deploy inputs. `site_name` is the full FQDN (Contract A) — the
	on-disk site dir name after the rename, the proxy Host header, and the Site
	key, one string never transformed. `warm_vm_uuid` is set when this VM was
	warm-restored from a golden memory snapshot: the deploy then asserts the
	in-guest identity freshen completed for exactly this VM before it renames.

	There is no per-VM admin password here: the baked throwaway Administrator
	password ships with the golden site and is rotated out of band, NOT reset on
	the signup path (resetting it cost a full CPU-throttled `bench frappe` boot —
	~28s under the 0.25-core cap — which dominated the deploy)."""

	site_name: str
	warm_vm_uuid: str = ""

	@classmethod
	def from_args(cls, argv: list[str] | None = None) -> "DeploySiteInputs":
		parser = argparse.ArgumentParser(prog="deploy-site", description=cls.__doc__)
		parser.add_argument("--site-name", required=True, help="Full FQDN, e.g. acme.blr1.frappe.dev")
		parser.add_argument(
			"--warm-vm-uuid",
			default="",
			help="This VM's uuid when it was warm-restored; gates on the in-guest freshen",
		)
		ns = parser.parse_args(argv)
		return cls(site_name=ns.site_name, warm_vm_uuid=ns.warm_vm_uuid)


@dataclass(frozen=True)
class DeploySiteResult:
	"""What the deploy records on the Task row for the operator's audit trail. `site`
	is the FQDN the deploy served; `serving` is the in-guest local probe's verdict."""

	site: str
	serving: bool

	def emit(self) -> None:
		print(RESULT_MARKER + json.dumps({"site": self.site, "serving": self.serving}))


def _env() -> dict:
	env = dict(os.environ)
	env["PATH"] = BAKED_PATH + ":" + env.get("PATH", "")
	env["DEBIAN_FRONTEND"] = "noninteractive"
	return env


def _run(args: list[str], *, capture: bool = False) -> str:
	"""Run a command, streaming to our stdout/stderr (so the controller's Task row
	captures the bench output) unless `capture`, in which case return stdout. Fail
	loud: a non-zero exit aborts the deploy (the controller marks the Site Failed)."""
	result = subprocess.run(
		args,
		env=_env(),
		text=True,
		capture_output=capture,
		check=True,
	)
	return result.stdout if capture else ""


def _bench(*args: str, capture: bool = False) -> str:
	"""Invoke the baked bench-cli against the baked bench (`bench -b atlas …`)."""
	return _run([BENCH, "-b", BENCH_NAME, *args], capture=capture)


def _await_freshen(warm_vm_uuid: str, timeout_seconds: int = 60) -> None:
	"""Gate a warm deploy on the in-guest identity freshen having completed for
	THIS VM. Reaching the guest over its own /128 already implies the network
	half happened (the freshen brings the clone's addresses up last), so the
	marker is normally present on the first read — the wait covers the
	marker-write race, the timeout the pathological 'reached over a stale path'
	case. Fail loud: deploying a site onto a clone that still carries the
	golden's identity must never proceed."""
	import time

	deadline = time.monotonic() + timeout_seconds
	while time.monotonic() < deadline:
		try:
			with open("/etc/atlas-vm-uuid") as handle:
				if handle.read().strip() == warm_vm_uuid:
					return
		except OSError:
			pass
		# Short poll: the marker is normally present on the very first read (the
		# freshen brings the network up LAST, so reaching the guest implies it's
		# done), so a tight interval just shaves the marker-write race off a path
		# the user is actively watching — not a busy-wait in practice.
		time.sleep(0.2)
	sys.exit(
		f"warm freshen did not complete for {warm_vm_uuid} within {timeout_seconds}s; "
		"this clone still carries the golden's identity"
	)


def _preflight() -> None:
	"""Assert this is a golden bench VM, not plain Ubuntu. A missing bench-cli, baked
	bench, or baked site means the VM was cloned from the wrong/old snapshot — fail
	loud before any per-site work (the wrong image is unrecoverable here, not
	retryable). The baked site must be present (under its baked name OR, on a re-run,
	already renamed to the FQDN): a clone with neither was built from a site-less
	snapshot and can never serve."""
	if not os.path.exists(BENCH):
		sys.exit(f"bench-cli not found at {BENCH}; this VM was not baked from the golden image")
	if not os.path.isdir(BENCH_DIR):
		sys.exit(f"baked bench {BENCH_DIR} missing; this VM was not baked from the golden image")


def _rename_site_to_fqdn(fqdn: str) -> bool:
	"""Rename the baked `sites/site.local` dir to `sites/<fqdn>` — the one piece of
	per-VM on-disk identity (Contract A). Returns True if it renamed, False if the
	rename was already done (a re-run / idempotency).

	The production gunicorn is multitenant (`frappe.app:application`, no `--site`),
	so it resolves the site from the request `Host` header per request with nothing
	cached at boot — the moment `sites/<fqdn>` exists and the vhost says
	`server_name <fqdn>`, the running workers serve it with NO restart. A directory
	rename within one filesystem is atomic and sub-millisecond.

	Fails loud if neither the baked dir nor an already-renamed `<fqdn>` dir exists:
	the clone came from a site-less snapshot and can never serve."""
	baked = os.path.join(SITES_DIR, BAKED_SITE)
	target = os.path.join(SITES_DIR, fqdn)
	if os.path.isdir(target):
		# Already renamed (idempotent re-run). The baked dir must be gone too — if
		# both exist something is wrong, but the FQDN dir is what serves, so proceed.
		return False
	if not os.path.isdir(baked):
		sys.exit(
			f"neither baked site {baked} nor renamed {target} exists; this VM was cloned "
			f"from a site-less snapshot, not the baked-site golden image — re-bake or fix "
			f"default_bench_snapshot"
		)
	os.rename(baked, target)
	return True


def _setup_nginx_for_fqdn(fqdn: str) -> None:
	"""Regenerate the bench's nginx vhost for the renamed site and reload — the
	per-VM front-door fix, with NO gunicorn/supervisor restart.

	`bench setup nginx` (NOT `setup production`) is pure bench-cli config-gen: it
	scans `sites/`, so it now finds `sites/<fqdn>` and emits a vhost with
	`server_name <fqdn>` (matching the proxy's forwarded Host — the old no-rename
	model needed a `default_server` catch-all precisely because the on-disk name
	didn't match; the rename removes that need) and a `root .../sites/<fqdn>/public`
	files block. It then `nginx -t`s and `systemctl reload`s — no Frappe boot, no
	process restart, sub-second.

	bench-cli only WRITES current sites' confs; it never deletes stale ones, so the
	baked `site.local.conf` would otherwise linger beside the new `<fqdn>.conf` with
	a dangling `server_name site.local`. Remove it before regenerating. Then add the
	IPv6 listener bench-cli omits (it binds v4-only) and reload once more."""
	stale = os.path.join(NGINX_SITES_DIR, f"{BAKED_SITE}.conf")
	try:
		os.remove(stale)
	except FileNotFoundError:
		pass
	_bench("setup", "nginx")
	_enable_ipv6_listeners()


def _enable_ipv6_listeners() -> None:
	"""Make the bench's per-site nginx vhosts listen on IPv6, then reload.

	`bench setup nginx` emits site vhosts with a bare `listen 80;` — which binds
	IPv4 ONLY. But the EDGE proxy reaches each site over the VM's public **/128
	(IPv6)** — the only inbound path (vm-inbound-ipv6-only). Without an explicit
	`listen [::]:80;` the site vhost never matches a v6 request, so the request
	falls through to whatever owns the v6 default — answering 404. The site serves
	fine on v4 and is dead on v6 (the path that matters): the south hop and the
	readiness probe both fail. So after `setup nginx` we add `listen [::]:80;`
	beside each `listen 80;` in the generated site vhosts and reload. Idempotent —
	re-adding is guarded by a presence check.

	No `default_server` is added: the rename gives the vhost a real `server_name
	<fqdn>` that matches the proxy's Host header, so the catch-all is unnecessary.
	(The stock Ubuntu default vhost, which grabbed [::]:80 default_server, is
	removed at bake time in build.sh.)"""
	if not os.path.isdir(NGINX_SITES_DIR):
		# Older bench-cli layouts inline vhosts in config/nginx.conf; fall back to
		# patching that single file so the fix is layout-agnostic.
		candidates = [os.path.join(BENCH_DIR, "config", "nginx.conf")]
	else:
		candidates = [
			os.path.join(NGINX_SITES_DIR, f) for f in os.listdir(NGINX_SITES_DIR) if f.endswith(".conf")
		]
	for conf in candidates:
		_add_ipv6_listen(conf)
	_run(["sudo", "systemctl", "reload", "nginx"])


def _add_ipv6_listen(conf_path: str) -> None:
	"""Add a v6 listener beside each `listen 80;` in a bench vhost: append
	`listen [::]:80;` after it.

	The EDGE proxy reaches the VM over its public /128, so without a v6 listener the
	vhost never matches a v6 request. No `default_server` — the renamed vhost's
	`server_name <fqdn>` already matches the proxy's forwarded Host.

	Pure text edit — no nginx-config parser in the guest (stdlib-only). Idempotent:
	a conf that already has the v6 listener is left untouched."""
	try:
		with open(conf_path) as f:
			text = f.read()
	except FileNotFoundError:
		return
	if "listen [::]:80" in text:
		return
	out_lines = []
	for line in text.splitlines(keepends=True):
		stripped = line.strip()
		if stripped == "listen 80;" or stripped.startswith("listen 80 "):
			indent = line[: len(line) - len(line.lstrip())]
			out_lines.append(line)
			out_lines.append(f"{indent}listen [::]:80;\n")
		else:
			out_lines.append(line)
	with open(conf_path, "w") as f:
		f.write("".join(out_lines))


def _serving(site_name: str) -> bool:
	"""Best-effort in-guest confirmation that the site answers locally before we
	report serving. The controller's wait_for_http is the authoritative gate
	(Contract B, end-to-end over the real network); this is a fast local sanity
	check so a deploy that silently failed to bring nginx up surfaces here too.

	Probe over **IPv6** (`[::1]`), not just v4 — the edge proxy reaches the site
	over its public /128, so a v4-only vhost serves 200 on 127.0.0.1 while the
	real (v6) path 404s. Checking v6 here makes that failure surface in-guest
	instead of only at the controller's wait_for_http minutes later. The Host
	header is the FQDN (Contract A): the multitenant gunicorn resolves the site
	from it, so a v4/v6 200 here proves the renamed site is wired end to end."""
	return _local_ping(site_name, "[::1]") and _local_ping(site_name, "127.0.0.1")


def _local_ping(site_name: str, host_ip: str) -> bool:
	try:
		out = subprocess.run(
			[
				"curl",
				"-s",
				"-g",
				"-o",
				"/dev/null",
				"-w",
				"%{http_code}",
				"-H",
				f"Host: {site_name}",
				f"http://{host_ip}:80/api/method/ping",
			],
			text=True,
			capture_output=True,
			timeout=30,
			check=False,
		)
		return out.stdout.strip() == "200"
	except Exception:
		return False


def _stage_logger():
	"""A tiny in-guest stage tracer: returns a `log(msg)` that prints `[deploy-site
	+Ns]` to stdout (captured on the controller's Task row + streamed to the job
	log), so the operator following auto_provision sees which in-guest step is slow.
	Stdlib-only, like the rest of this script."""
	import time

	t0 = time.monotonic()

	def log(message: str) -> None:
		print(f"[deploy-site +{time.monotonic() - t0:5.1f}s] {message}", flush=True)

	return log


def main() -> None:
	"""Deploy one site into a golden bench VM — the RENAME model.

	The baked `site.local` is renamed to the per-VM FQDN, so the on-disk site name
	== the proxy Host header == the Site key (Contract A). The production gunicorn
	is multitenant (no `--site`), resolving the site from the request `Host` per
	request, so the rename + the regenerated `server_name <fqdn>` vhost take effect
	with NO restart.

	The deploy is: (warm) gate on the identity freshen → rename the site dir →
	`bench setup nginx` (regenerate the vhost + reload) → add the v6 listener +
	reload → local serving probe. No `set-admin-password` (the baked throwaway is
	rotated out of band), no `setup production`, no restart of gunicorn/supervisor —
	that absence is the whole latency win.

	A warm clone (resumed from a memory snapshot) is already serving `site.local`;
	a cold clone (a freshly image-provisioned VM whose bench was never brought up)
	additionally needs the production stack up first."""
	inputs = DeploySiteInputs.from_args()
	log = _stage_logger()
	log(
		f"deploy start (fqdn={inputs.site_name}, baked={BAKED_SITE}, "
		f"{'warm' if inputs.warm_vm_uuid else 'cold'})"
	)
	_preflight()
	if inputs.warm_vm_uuid:
		log("awaiting warm identity freshen marker …")
		_await_freshen(inputs.warm_vm_uuid)
		log("freshen complete")

	# COLD only: bring the bench up. A warm clone is already serving site.local;
	# `setup production` starts nginx + supervisor against the baked dir, which the
	# rename below then repoints. (The cold path is the slow fallback — warm is the
	# self-serve path.)
	if not inputs.warm_vm_uuid:
		log("cold: bench setup production (nginx + supervisor) …")
		_bench("setup", "production")
		log("cold bring-up done")

	# The per-VM on-disk identity: rename the baked site to the FQDN.
	log("renaming baked site to the FQDN …")
	renamed = _rename_site_to_fqdn(inputs.site_name)
	log(f"rename {'done' if renamed else 'already in place'}")

	# Regenerate the nginx vhost for the renamed site (server_name <fqdn> + v6
	# listener) and reload — no gunicorn/supervisor restart.
	log("regenerating nginx vhost (setup nginx + v6 listener) …")
	_setup_nginx_for_fqdn(inputs.site_name)
	log("nginx vhost regenerated + reloaded")

	log("local serving probe (v6 + v4) …")
	serving = _serving(inputs.site_name)
	log(f"deploy complete (serving={serving})")
	result = DeploySiteResult(site=inputs.site_name, serving=serving)
	result.emit()


if __name__ == "__main__":
	main()
