"""Unit tests for resize-vm's jailer-launch.sh cgroup rewrite.

The resize task rewrites two independent memory ceilings: guest RAM in
firecracker.json AND the host cgroup memory.max in jailer-launch.sh. This pins
the launcher splice — a stale memory.max caps the guest below its new RAM and
the kernel OOM-kills Firecracker (CONSTRAINT_MEMCG) on the next boot.

Stdlib-only — run with `python3 -m unittest atlas.test_resize_vm` from scripts/lib.
"""

import unittest
from unittest import mock

from atlas import _cli

resize_vm = _cli._load(_cli._stems()["resize-vm"])


# A launcher shaped exactly like provision-vm._jailer_launch emits: the two
# --cgroup value lines are contiguous, each `    --cgroup <value> \`.
LAUNCHER = """\
#!/bin/bash
# GENERATED by provision-vm.py for VM abc. Do not edit.
set -euo pipefail

boot_args=(--config-file firecracker.json)

exec /usr/local/bin/jailer \\
    --id abc \\
    --exec-file /usr/local/bin/firecracker \\
    --uid 218817 \\
    --gid 218817 \\
    --cgroup-version 2 \\
    --netns /var/run/netns/atlas-abc \\
    --cgroup memory.max=2415919104 \\
    --cgroup memory.swap.max=0 \\
    --cgroup cpu.weight=25 \\
    --cgroup 'cpu.max=200000 100000' \\
    --resource-limit no-file=1024 \\
    --chroot-base-dir /var/lib/atlas/virtual-machines/abc/jail \\
    -- \\
    --api-sock run/firecracker.socket \\
    "${boot_args[@]}"
"""


class RewriteLauncherCgroups(unittest.TestCase):
	def _rewrite(self, cgroup_arg, launcher=LAUNCHER):
		"""Run the rewrite against an in-memory launcher; return the installed text."""
		installed = {}

		def fake_run(command, *params, **kwargs):
			# `sudo cat <launcher>` returns the launcher; chown/mv are no-ops.
			return launcher if command.startswith("sudo cat") else ""

		def fake_install_file(content, dest, **kwargs):
			installed["content"] = content
			installed["dest"] = dest
			installed["mode"] = kwargs.get("mode")

		with (
			mock.patch.object(resize_vm, "run", side_effect=fake_run),
			mock.patch.object(resize_vm, "install_file", side_effect=fake_install_file),
		):
			resize_vm._rewrite_launcher_cgroups("/path/jailer-launch.sh", cgroup_arg)
		return installed

	def test_replaces_memory_max_and_cpu(self) -> None:
		new = [
			"memory.max=8858370048",
			"memory.swap.max=0",
			"cpu.max=400000 100000",
		]
		out = self._rewrite(new)
		text = out["content"]
		# New caps present, old ones gone.
		self.assertIn("--cgroup memory.max=8858370048 \\", text)
		self.assertNotIn("2415919104", text)
		self.assertNotIn("cpu.weight=25", text)
		# cpu.max's internal space is preserved as one shlex-quoted token.
		self.assertIn("--cgroup 'cpu.max=400000 100000' \\", text)
		# Installed executable, to the same path (via .new then mv, so dest is .new).
		self.assertEqual(out["mode"], "0755")

	def test_preserves_surrounding_lines(self) -> None:
		out = self._rewrite(["memory.max=1", "memory.swap.max=0", "cpu.max=100000 100000"])
		text = out["content"]
		# The boot-args block, uid, netns, resource-limit, chroot, api-sock all survive.
		for keep in (
			"boot_args=(--config-file firecracker.json)",
			"--uid 218817 \\",
			"--netns /var/run/netns/atlas-abc \\",
			"--resource-limit no-file=1024 \\",
			"--chroot-base-dir /var/lib/atlas/virtual-machines/abc/jail \\",
			'"${boot_args[@]}"',
		):
			self.assertIn(keep, text)

	def test_cgroup_lines_stay_contiguous_in_place(self) -> None:
		# The new --cgroup block sits exactly where the old one did: right after
		# --netns and right before --resource-limit.
		out = self._rewrite(["memory.max=9", "cpu.max=100000 100000"])
		lines = [ln.strip() for ln in out["content"].splitlines()]
		netns = lines.index("--netns /var/run/netns/atlas-abc \\")
		self.assertEqual(lines[netns + 1], "--cgroup memory.max=9 \\")
		self.assertEqual(lines[netns + 2], "--cgroup 'cpu.max=100000 100000' \\")
		self.assertEqual(lines[netns + 3], "--resource-limit no-file=1024 \\")

	def test_refuses_launcher_with_no_cgroup_lines(self) -> None:
		# A launcher this rewrite doesn't understand must fail loud, never boot with
		# the stale caps this rewrite exists to replace.
		with self.assertRaises(SystemExit):
			self._rewrite(["memory.max=1"], launcher="#!/bin/bash\nexec /usr/local/bin/jailer --id abc\n")


if __name__ == "__main__":
	unittest.main()
