#!/bin/sh

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case "${1:-}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules dm_crypt
copy_exec /usr/sbin/cryptsetup /usr/sbin
copy_exec /usr/sbin/blkid /usr/sbin
