#!/bin/sh

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case "${1:-}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# shellcheck source=/usr/share/initramfs-tools/hook-functions
# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

manual_add_modules dm_crypt
copy_exec /usr/sbin/cryptsetup /usr/sbin
copy_exec /usr/sbin/blkid /usr/sbin
copy_exec /usr/sbin/dumpe2fs /usr/sbin
copy_exec /usr/sbin/blockdev /usr/sbin
