#!/usr/bin/env python3
# Resize a Stopped VM: set vCPU/memory in its firecracker config, rewrite the
# jailer's cgroup caps, and grow the rootfs to DISK_GB. Firecracker reads
# machine-config only at boot, so the VM must be Stopped — the next Start picks
# up the new config. Disk only grows (the caller rejects shrink). Idempotent:
# re-running writes the same values and resize2fs is a no-op once the filesystem
# already fills the device.
#
# The cgroup rewrite is load-bearing, not cosmetic: the guest RAM in
# firecracker.json and the host cgroup memory.max in jailer-launch.sh are two
# INDEPENDENT ceilings. Resizing only firecracker.json hands the guest RAM the
# cgroup still caps below — the guest allocates past memory.max and the kernel
# OOM-kills Firecracker (CONSTRAINT_MEMCG, "Failed with result 'signal'"). So the
# controller forwards fresh CGROUP_ARG (derived from the new memory/cpu, exactly
# as provision does) and we splice the new `--cgroup` lines into the launcher.
#
# Successor to resize-vm.sh. Inputs are now typed CLI flags parsed once by
# ResizeInputs.from_args() (vcpus/memory-mb/disk-gb declared `int` so argparse
# coerces and rejects non-integers). No machine-readable result — the controller
# reads nothing back, so we print only the human "Resized ..." line.

import os
import shlex
import sys
import typing
from dataclasses import dataclass, field

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))

from atlas._run import install_file, run
from atlas._task import TaskInputs
from atlas.lvm import ThinPool
from atlas.paths import VirtualMachinePaths


@dataclass(frozen=True)
class ResizeInputs(TaskInputs):
	"""Resize a Stopped VM's vCPU/memory (next boot) and grow its rootfs."""

	command: typing.ClassVar[str] = "resize-vm"
	virtual_machine_name: str  # UUID; locates the VM directory and disk LV
	vcpus: int
	memory_mb: int
	disk_gb: int  # target rootfs size; grow-only
	# The new jailer cgroup VALUES (memory.max=…, cpu.max=…/cpu.weight=…), one per
	# repeatable --cgroup-arg flag — same shape provision passes. Derived by the
	# controller from the new memory/cpu via atlas.networking.cgroup_args, so the
	# launcher's caps track the resize instead of pinning the pre-resize memory.max.
	cgroup_arg: list = field(default_factory=list)
	# Data disk (the root disk's peer), grow-only. 0 = the VM has no data disk.
	# data_disk_format is an int (0/1), not a bool — see provision-vm.py.
	data_disk_gb: int = 0
	data_disk_format: int = 1


def _rewrite_launcher_cgroups(launcher_path: str, cgroup_arg: list) -> None:
	"""Replace the `--cgroup <value> \\` lines in the generated jailer-launch.sh
	with ones rendered from the new cgroup values, leaving every other line (the
	boot-args block, uid/netns, --resource-limit, chroot) byte-for-byte intact.

	The launcher is GENERATED by provision-vm._jailer_launch, which emits each
	cgroup value on its own continued line as `    --cgroup <shlex.quote(value)> \\`.
	We match that exact shape: the `--cgroup` lines are contiguous, so we drop the
	old run and splice the new one at the first line's position, preserving order.
	Rendering matches _jailer_launch verbatim (same indent, same shlex.quote) so a
	re-provision after a resize produces an identical launcher — no drift."""
	original = run("sudo cat {}", launcher_path)
	lines = original.splitlines()
	rendered = [f"    --cgroup {shlex.quote(value)} \\" for value in cgroup_arg]

	cgroup_indices = [i for i, line in enumerate(lines) if line.lstrip().startswith("--cgroup ")]
	if not cgroup_indices:
		# A launcher with no --cgroup lines is not one this rewrite understands
		# (hand-edited, or a format change): fail loud rather than silently boot
		# with the stale caps that caused the OOM this rewrite exists to prevent.
		sys.exit(f"{launcher_path} has no --cgroup lines to rewrite; refusing to leave stale caps")
	first = cgroup_indices[0]
	# Contiguity is the generator's invariant; assert it so a future launcher that
	# interleaves other flags between --cgroup lines fails here instead of dropping
	# a non-cgroup line into the replaced span.
	if cgroup_indices != list(range(first, first + len(cgroup_indices))):
		sys.exit(f"{launcher_path} --cgroup lines are not contiguous; refusing to rewrite")
	new_lines = lines[:first] + rendered + lines[first + len(cgroup_indices) :]

	new_launcher = "\n".join(new_lines) + "\n"
	install_file(new_launcher, f"{launcher_path}.new", mode="0755")
	run("sudo chown {} {}", f"--reference={launcher_path}", f"{launcher_path}.new")
	run("sudo mv {} {}", f"{launcher_path}.new", launcher_path)


def main() -> None:
	inputs = ResizeInputs.from_args()
	pool = ThinPool()

	# Config lives inside the VM's jail; the disk is the VM's LV.
	paths = VirtualMachinePaths(inputs.virtual_machine_name)
	config_path = paths.firecracker_config
	disk = pool.vm_disk(inputs.virtual_machine_name)

	if not os.path.isfile(config_path):
		sys.exit(f"firecracker config {config_path} missing; provision the VM first")
	if not disk.exists:
		sys.exit(f"disk LV {disk.name} missing; provision the VM first")

	# The machine config (and possibly the disk) is about to change under any
	# pending memory snapshot; the saved vmstate would no longer match. Drop it
	# so the next Start cold-boots with the new config.
	run("sudo rm -rf {}", paths.memory_snapshot_directory)

	# 1. Rewrite machine-config in place. jq edits only the two keys, preserving
	#    boot-source, drives and network-interfaces. The replacement file is created
	#    by root; copy the original's owner onto it so the jailed Firecracker (the
	#    per-VM uid) can still read its config after chroot.
	new_config = run(
		"sudo jq --argjson vcpus {} --argjson mem {} {} {}",
		str(inputs.vcpus),
		str(inputs.memory_mb),
		'."machine-config".vcpu_count = $vcpus | ."machine-config".mem_size_mib = $mem',
		config_path,
	)
	install_file(new_config, f"{config_path}.new", mode="0644")
	run("sudo chown {} {}", f"--reference={config_path}", f"{config_path}.new")
	run("sudo mv {} {}", f"{config_path}.new", config_path)

	# 1b. Rewrite the jailer's cgroup caps in jailer-launch.sh. firecracker.json
	#     (guest RAM) and the launcher's `--cgroup memory.max` (host process ceiling)
	#     are independent ceilings; leaving the launcher stale caps the guest below
	#     the RAM it was just given → CONSTRAINT_MEMCG OOM-kill on the next boot. Only
	#     rewritten when the controller passed CGROUP_ARG (a bare hand-run may omit it,
	#     leaving the launcher untouched — the old vCPU/mem-only behavior).
	if inputs.cgroup_arg:
		_rewrite_launcher_cgroups(paths.jailer_launch, inputs.cgroup_arg)

	# 2. Grow the disk LV to DISK_GB. lvextend -r extends the LV and the ext4 on it
	#    in one shot. Disk only ever grows (shrink is rejected upstream); lvextend
	#    refuses to shrink and is a clean no-op when the LV already meets the size,
	#    so a re-run (or a resize that only changed vCPU/memory) does not error.
	run("sudo lvextend -r -L {} {}", f"{inputs.disk_gb}G", disk.device_path, check=False, quiet=True)

	# 3. Grow the data disk (the root disk's peer) when present. Grow-only, same as
	#    root: -r resizes the ext4 too when formatted, else the block device only.
	#    Skipped when the VM has no data disk; a clean no-op when the LV already
	#    meets the size (idempotent re-run, or a resize that only touched vCPU/mem).
	#    The controller rejects 0→N, so a data_disk_gb here always has a live LV.
	if inputs.data_disk_gb > 0:
		data_disk = pool.data_disk(inputs.virtual_machine_name)
		if data_disk.exists:
			grow = "sudo lvextend"
			grow += " -r" if inputs.data_disk_format else ""
			grow += " -L {} {}"
			run(grow, f"{inputs.data_disk_gb}G", data_disk.device_path, check=False, quiet=True)

	print(
		f"Resized {inputs.virtual_machine_name}: "
		f"{inputs.vcpus} vCPU, {inputs.memory_mb} MB, {inputs.disk_gb} GB"
		+ (f", data {inputs.data_disk_gb} GB." if inputs.data_disk_gb > 0 else ".")
	)


if __name__ == "__main__":
	main()
